server:
  port: 8000
  shutdown: graceful

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      routes:
        - id: crawler-service
          uri: ${CRAWLER_SERVICE_URL:http://localhost:8001}
          predicates:
            - Path=/ehcrawler/**
          filters:
            - RewritePath=/ehcrawler/?(?<segment>.*), /${segment}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

  mvc:
    problemdetails:
      enabled: true

springdoc:
  swagger-ui:
    use-root-path: true